name: langchain_tutorial
channels:
  - default
dependencies:
  - python=3.10.12
  - pip=23.1.2
  - pip:
      - langchain==0.2.1
      - langchain-experimental==0.0.59
      - langchain-openai==0.1.7
      - langchainhub==0.1.16
      - huggingface-hub==0.22.2